#!/bin/bash
PORT=`cat /etc/apache2/ports.conf | grep "^Listen" | awk '{print $2}'`
curl -s localhost:$PORT | grep "Error establishing a database connection" >/dev/null && service mysql restart && echo "Restarted mysql"
